# Generated by Django 4.2.4 on 2023-08-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_news_category_alter_newscategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
