# Generated by Django 4.2.4 on 2023-08-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_newscomment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
