# Generated by Django 4.2.4 on 2023-08-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_news_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='document_id',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
