# Generated by Django 4.2.4 on 2023-08-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_news_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
