# Generated by Django 4.2.4 on 2023-08-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_newscategory_id_alter_newscomment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
