# Generated by Django 4.2.4 on 2023-09-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_newscomment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.news')),
            ],
        ),
    ]
